#!/bin/bash

echo "releasing http-spec..."

(
  go install .                         && \
  docker build -t tmornini/http-spec . && \
  docker push tmornini/http-spec
  # docker run tmornini/http-spec        && \
) && exit 0

echo "$0 failed"

exit 1
