#!/bin/bash

time (
  http-spec examples/file-not-found.htsf                   && exit 1
  http-spec examples/line-count-mismatch.htsf              && exit 1
  http-spec examples/request-only.htsf                     && exit 1
  http-spec examples/uuid.htsf                             && exit 1
  http-spec examples/random-uuid.htsf                      && exit 1
  http-spec examples/malformed-prefix.htsf                 && exit 1

  http-spec examples/not-found.htsf                        \
            examples/post.htsf                             \
            examples/regexp-and-substitution.htsf          \
            examples/sleep.htsf                            || exit 1

  http-spec -skip-tls-verification examples/insecure.htsf  || exit 1

  http-spec examples/do-not-follow-redirect.htsf           || exit 1

  http-spec examples/built-in-substitution.htsf            || exit 1

  http-spec -matchers matchers.json                         \
            examples/custom-matcher.htsf                   || exit 1

  http-spec -hostname httpbin.org -scheme http              \
            examples/scheme-and-hostname-1.htsf            || exit 1

  http-spec -hostname httpbin.org -scheme https             \
            examples/scheme-and-hostname-2.htsf            || exit 1

  http-spec examples/multiple-matchers.htsf                || exit 1

  output=$(http-spec -http-timeout 1ms                        \
                     -max-http-attempts 1                    \
                     examples/not-found.htsf 2>&1)          && exit 1
  echo "$output" | grep -qi 'timeout'                        || exit 1

  SECONDS=0
  output=$(http-spec -retry-status-codes 404                 \
                     -max-http-attempts 2                    \
                     -http-retry-delay 1s                    \
                     examples/not-found.htsf 2>&1)          && exit 1
  [ $SECONDS -ge 1 ]                                         || exit 1
  echo "$output" | grep -q 'retry limit reached'             || exit 1

  output=$(http-spec -show-substitutions                     \
                     examples/malformed-prefix.htsf 2>&1)   && exit 1
  echo "$output" | grep -q 'Substitutions'                    || exit 1

  output=$(http-spec examples/malformed-prefix.htsf 2>&1)   && exit 1
  ! echo "$output" | grep -q 'Substitutions'                || exit 1
) || exit 1

echo
echo Tests ran successfully!

exit 0
