#!/bin/bash

time (
  http-spec examples/file-not-found.htsf                   && exit 1
  http-spec examples/line-count-mismatch.htsf              && exit 1
  http-spec examples/request-only.htsf                     && exit 1
  http-spec examples/uuid.htsf                             && exit 1
  http-spec examples/random-uuid.htsf                      && exit 1
  http-spec examples/malformed-prefix.htsf                 && exit 1

  http-spec examples/not-found.htsf                        \
            examples/post.htsf                             \
            examples/regexp-and-substitution.htsf          \
            examples/sleep.htsf                            || exit 1

  http-spec -skip-tls-verification examples/insecure.htsf  || exit 1

  http-spec examples/do-not-follow-redirect.htsf           || exit 1

  http-spec examples/built-in-substitution.htsf            || exit 1

  http-spec -matchers matchers.json                         \
            examples/custom-matcher.htsf                   || exit 1

  http-spec -hostname httpbin.org -scheme http              \
            examples/scheme-and-hostname-1.htsf            || exit 1

  http-spec -hostname httpbin.org -scheme https             \
            examples/scheme-and-hostname-2.htsf            || exit 1

  http-spec examples/multiple-matchers.htsf                || exit 1
) || exit 1

echo
echo Tests ran successfully!

exit 0
