#!/bin/bash

echo "validating http-spec..."

http_spec_containers=$(docker ps -aq \
  --filter ancestor=tmornini/http-spec \
  --filter ancestor=tmornini/validate-http-spec)
[ -n "$http_spec_containers" ] && docker rm $http_spec_containers

for image in tmornini/http-spec tmornini/validate-http-spec; do
  image_ids=$(docker images -q "$image")
  [ -n "$image_ids" ] && docker rmi -f $image_ids
done

(
  go install .                                                        && \
  docker build -t tmornini/http-spec .                                && \
  docker build -t tmornini/validate-http-spec -f examples/Dockerfile . && \
  docker run --rm tmornini/validate-http-spec
) && exit 0

echo "$0 failed"

exit 1
