#!/bin/bash

time (
  # http-spec example-file-not-found.htsf                  && exit 1
  # http-spec example-line-count-mismatch.htsf             && exit 1
  # http-spec example-request-only.htsf                    && exit 1
  # http-spec example-uuid.htsf                            && exit 1

  http-spec example-file-not-found.htsf                  \
            example-line-count-mismatch.htsf             \
            example-request-only.htsf                    \
            example-uuid.htsf                            && exit 1

  http-spec example-not-found.htsf                       \
            example-post.htsf                            \
            example-regexp-and-substitution.htsf         \
            example-sleep.htsf                           || exit 1

  http-spec -skip-tls-verification example-insecure.htsf || exit 1

  http-spec example-do-not-follow-redirect.htsf          || exit 1

  http-spec example-built-in-substitution.htsf           || exit 1
) || exit 1

echo
echo Tests ran successfully!

exit 0
